# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_material', [dirname(__file__)])
        except ImportError:
            import _material
            return _material
        if fp is not None:
            try:
                _mod = imp.load_module('_material', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _material = swig_import_helper()
    del swig_import_helper
else:
    import _material
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


ELASTIC = _material.ELASTIC
ABSORPTION = _material.ABSORPTION
CAPTURE = _material.CAPTURE
FISSION = _material.FISSION
TOTAL = _material.TOTAL
ISOTROPIC_CM = _material.ISOTROPIC_CM
ISOTROPIC_LAB = _material.ISOTROPIC_LAB
class Isotope(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Isotope, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Isotope, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _material.new_Isotope(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _material.delete_Isotope
    __del__ = lambda self : None;
    def parseName(self): return _material.Isotope_parseName(self)
    def getIsotopeType(self): return _material.Isotope_getIsotopeType(self)
    def getA(self): return _material.Isotope_getA(self)
    def getAlpha(self): return _material.Isotope_getAlpha(self)
    def getN(self): return _material.Isotope_getN(self)
    def getAO(self): return _material.Isotope_getAO(self)
    def getTemperature(self): return _material.Isotope_getTemperature(self)
    def getMuAverage(self): return _material.Isotope_getMuAverage(self)
    def isFissionable(self): return _material.Isotope_isFissionable(self)
    def getElasticXS(self, *args): return _material.Isotope_getElasticXS(self, *args)
    def getElasticAngleType(self): return _material.Isotope_getElasticAngleType(self)
    def getAbsorptionXS(self, *args): return _material.Isotope_getAbsorptionXS(self, *args)
    def getCaptureXS(self, *args): return _material.Isotope_getCaptureXS(self, *args)
    def getFissionXS(self, *args): return _material.Isotope_getFissionXS(self, *args)
    def getTotalXS(self, *args): return _material.Isotope_getTotalXS(self, *args)
    def getTransportXS(self, *args): return _material.Isotope_getTransportXS(self, *args)
    def usesThermalScattering(self): return _material.Isotope_usesThermalScattering(self)
    def setIsotopeType(self, *args): return _material.Isotope_setIsotopeType(self, *args)
    def setA(self, *args): return _material.Isotope_setA(self, *args)
    def setAO(self, *args): return _material.Isotope_setAO(self, *args)
    def setN(self, *args): return _material.Isotope_setN(self, *args)
    def setTemperature(self, *args): return _material.Isotope_setTemperature(self, *args)
    def makeFissionable(self): return _material.Isotope_makeFissionable(self)
    def loadXS(self, *args): return _material.Isotope_loadXS(self, *args)
    def setElasticXS(self, *args): return _material.Isotope_setElasticXS(self, *args)
    def setElasticAngleType(self, *args): return _material.Isotope_setElasticAngleType(self, *args)
    def setAbsorptionXS(self, *args): return _material.Isotope_setAbsorptionXS(self, *args)
    def setFissionXS(self, *args): return _material.Isotope_setFissionXS(self, *args)
    def generateCaptureXS(self): return _material.Isotope_generateCaptureXS(self)
    def rescaleXS(self, *args): return _material.Isotope_rescaleXS(self, *args)
    def clone(self): return _material.Isotope_clone(self)
    def getCollisionType(self, *args): return _material.Isotope_getCollisionType(self, *args)
    def getThermalScatteringEnergy(self, *args): return _material.Isotope_getThermalScatteringEnergy(self, *args)
    def initializeThermalScattering(self, *args): return _material.Isotope_initializeThermalScattering(self, *args)
    def thermalScatteringProb(self, *args): return _material.Isotope_thermalScatteringProb(self, *args)
Isotope_swigregister = _material.Isotope_swigregister
Isotope_swigregister(Isotope)

EQUAL = _material.EQUAL
LOGARITHMIC = _material.LOGARITHMIC
OTHER = _material.OTHER
GRAMCM3 = _material.GRAMCM3
NUMCM3 = _material.NUMCM3
class Material(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Material, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Material, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _material.new_Material()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _material.delete_Material
    __del__ = lambda self : None;
    def getMaterialName(self): return _material.Material_getMaterialName(self)
    def getTotalNumberDensity(self): return _material.Material_getTotalNumberDensity(self)
    def getIsotope(self, *args): return _material.Material_getIsotope(self, *args)
    def getIsotopeNumDensity(self, *args): return _material.Material_getIsotopeNumDensity(self, *args)
    def getTotalMacroXS(self, *args): return _material.Material_getTotalMacroXS(self, *args)
    def getTotalMicroXS(self, *args): return _material.Material_getTotalMicroXS(self, *args)
    def getElasticMacroXS(self, *args): return _material.Material_getElasticMacroXS(self, *args)
    def getElasticMicroXS(self, *args): return _material.Material_getElasticMicroXS(self, *args)
    def getAbsorptionMacroXS(self, *args): return _material.Material_getAbsorptionMacroXS(self, *args)
    def getAbsorptionMicroXS(self, *args): return _material.Material_getAbsorptionMicroXS(self, *args)
    def getCaptureMacroXS(self, *args): return _material.Material_getCaptureMacroXS(self, *args)
    def getCaptureMicroXS(self, *args): return _material.Material_getCaptureMicroXS(self, *args)
    def getFissionMacroXS(self, *args): return _material.Material_getFissionMacroXS(self, *args)
    def getFissionMicroXS(self, *args): return _material.Material_getFissionMicroXS(self, *args)
    def getTransportMicroXS(self, *args): return _material.Material_getTransportMicroXS(self, *args)
    def getTransportMacroXS(self, *args): return _material.Material_getTransportMacroXS(self, *args)
    def setDensity(self, *args): return _material.Material_setDensity(self, *args)
    def getDensity(self): return _material.Material_getDensity(self)
    def isRescaled(self): return _material.Material_isRescaled(self)
    def getEnergyGridIndex(self, *args): return _material.Material_getEnergyGridIndex(self, *args)
    def setMaterialName(self, *args): return _material.Material_setMaterialName(self, *args)
    def addIsotope(self, *args): return _material.Material_addIsotope(self, *args)
    def rescaleCrossSections(self, *args): return _material.Material_rescaleCrossSections(self, *args)
    def sampleIsotope(self, *args): return _material.Material_sampleIsotope(self, *args)
Material_swigregister = _material.Material_swigregister
Material_swigregister(Material)

# This file is compatible with both classic and new-style classes.


