.TH "pinspec/src/ Directory Reference" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarraycreator\&.h\fP"
.br
.RI "\fIFunctions for creating arrays with similar syntax to MATLAB\&. \fP"
.ti -1c
.RI "file \fBFissioner\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFissioner\&.h\fP"
.br
.RI "\fIThe \fBFissioner\fP class for fission neutron emission\&. \fP"
.ti -1c
.RI "file \fBGeometry\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGeometry\&.h\fP"
.br
.RI "\fIThe \fBGeometry\fP class\&. \fP"
.ti -1c
.RI "file \fBintegrate\&.h\fP"
.br
.RI "\fIUtility functions for numerical integration of 1D functions\&. \fP"
.ti -1c
.RI "file \fBinterpolate\&.h\fP"
.br
.RI "\fIUtility functions for linear interpolation of 1D functions\&. \fP"
.ti -1c
.RI "file \fBIsotope\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIsotope\&.h\fP"
.br
.RI "\fIThe \fBIsotope\fP class\&. \fP"
.ti -1c
.RI "file \fBlog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlog\&.h\fP"
.br
.RI "\fIUtility functions for writing log messages to the screen\&. \fP"
.ti -1c
.RI "file \fBMaterial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMaterial\&.h\fP"
.br
.RI "\fIThe \fBMaterial\fP class\&. \fP"
.ti -1c
.RI "file \fBNeutron\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNeutron\&.h\fP"
.br
.RI "\fIThe neutron C structure\&. \fP"
.ti -1c
.RI "file \fBRegion\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRegion\&.h\fP"
.br
.RI "\fIThe \fBRegion\fP class\&. \fP"
.ti -1c
.RI "file \fBSurface\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSurface\&.h\fP"
.br
.RI "\fIThe \fBSurface\fP class\&. \fP"
.ti -1c
.RI "file \fBTally\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTally\&.h\fP"
.br
.RI "\fIThe \fBTally\fP superclass and subclasses\&. \fP"
.ti -1c
.RI "file \fBTallyBank\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTallyBank\&.h\fP"
.br
.RI "\fIThe \fBTallyBank\fP static class\&. \fP"
.ti -1c
.RI "file \fBTallyFactory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTallyFactory\&.h\fP"
.br
.RI "\fIThe \fBTallyFactory\fP class\&. \fP"
.ti -1c
.RI "file \fBTimer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTimer\&.h\fP"
.br
.RI "\fIThe \fBTimer\fP static class\&. \fP"
.ti -1c
.RI "file \fBxsreader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBxsreader\&.h\fP"
.br
.RI "\fIUtility functions to parse in ENDF cross-sections from text files into data arrays\&. \fP"
.in -1c
