.TH "pinspec/src/arraycreator.h" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/arraycreator.h \- 
.PP
Functions for creating arrays with similar syntax to MATLAB\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename U > U * \fBlinspace\fP (T start, T end, int num_values)"
.br
.RI "\fICreates an array of equally spaced values\&. \fP"
.ti -1c
.RI "template<typename T , typename U > U * \fBlogspace\fP (T start, T end, int num_values)"
.br
.RI "\fICreates an array of equal logarithmically spaced values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions for creating arrays with similar syntax to MATLAB\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 28, 2012 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename T , typename U > U* linspace (Tstart, Tend, intnum_values)"

.PP
Creates an array of equally spaced values\&. Helper function to generate an array of equally spaced values between a specified start and end point\&. Modeled after MATLAB's linspace function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstart\fP the starting point 
.br
\fIend\fP the ending point 
.br
\fInum_values\fP the number of values to create 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the array of points 
.RE
.PP

.SS "template<typename T , typename U > U* logspace (Tstart, Tend, intnum_values)"

.PP
Creates an array of equal logarithmically spaced values\&. Helper function to generate an array of equal logarithmically spaced values between a specified start and end point\&. Modeled after MATLAB's logspace function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstart\fP the starting point 
.br
\fIend\fP the ending point 
.br
\fInum_values\fP the number of values to create 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the array of points 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
