.TH "DerivedTally" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedTally \- 
.PP
A class for tallies resulting from tally arithmetic operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDerivedTally\fP (const char *tally_name=(char *)'')"
.br
.RI "\fI\fBDerivedTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain type to UNDEFINED and the tally type to DERIVED\&. \fP"
.ti -1c
.RI "void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)"
.br
.RI "\fIA DERIVED tally cannot tally anything, and will throw an exception\&. \fP"
.ti -1c
.RI "void \fBsetTallyName\fP (char *tally_name)"
.br
.RI "\fISets the tally name\&. \fP"
.ti -1c
.RI "void \fBsetTallies\fP (double **tallies)"
.br
.RI "\fIAssigns an array for the tally values\&. \fP"
.ti -1c
.RI "void \fBsetBatchMu\fP (double *batch_mu)"
.br
.RI "\fIAssigns an array for the tally batch averages\&. \fP"
.ti -1c
.RI "void \fBsetBatchVariance\fP (double *batch_variance)"
.br
.RI "\fIAssigns an array for the tally batch variances\&. \fP"
.ti -1c
.RI "void \fBsetBatchStdDev\fP (double *batch_std_dev)"
.br
.RI "\fIAssigns an array for the tally batch standard deviations\&. \fP"
.ti -1c
.RI "void \fBsetBatchRelErr\fP (double *batch_rel_err)"
.br
.RI "\fIAssigns an array for the tally batch relative errors\&. \fP"
.ti -1c
.RI "void \fBsetComputedBatchStatistics\fP (bool computed)"
.br
.RI "\fIAssigns whether or not the tally has computed batch statistics\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A class for tallies resulting from tally arithmetic operations\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DerivedTally::DerivedTally (const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBDerivedTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain type to UNDEFINED and the tally type to DERIVED\&. \fBParameters:\fP
.RS 4
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void DerivedTally::setBatchMu (double *batch_mu)"

.PP
Assigns an array for the tally batch averages\&. \fBParameters:\fP
.RS 4
\fIbatch_mu\fP an array of tally averages 
.RE
.PP

.SS "void DerivedTally::setBatchRelErr (double *batch_rel_err)"

.PP
Assigns an array for the tally batch relative errors\&. \fBParameters:\fP
.RS 4
\fIbatch_rel_err\fP an array of tally relative errors 
.RE
.PP

.SS "void DerivedTally::setBatchStdDev (double *batch_std_dev)"

.PP
Assigns an array for the tally batch standard deviations\&. \fBParameters:\fP
.RS 4
\fIbatch_std_dev\fP an array of tally standard deviations 
.RE
.PP

.SS "void DerivedTally::setBatchVariance (double *batch_variance)"

.PP
Assigns an array for the tally batch variances\&. \fBParameters:\fP
.RS 4
\fIbatch_variance\fP an array of tally variances 
.RE
.PP

.SS "void DerivedTally::setComputedBatchStatistics (boolcomputed)"

.PP
Assigns whether or not the tally has computed batch statistics\&. \fBParameters:\fP
.RS 4
\fIcomputed\fP true if batch statistics are computed; otherwise false 
.RE
.PP

.SS "void DerivedTally::setTallies (double **tallies)"

.PP
Assigns an array for the tally values\&. \fBParameters:\fP
.RS 4
\fItallies\fP an array of tally values 
.RE
.PP

.SS "void DerivedTally::setTallyName (char *tally_name)"

.PP
Sets the tally name\&. \fBParameters:\fP
.RS 4
\fItally_name\fP the name of the tally\&. 
.RE
.PP

.SS "void DerivedTally::tally (\fBneutron\fP *neutron)\fC [virtual]\fP"

.PP
A DERIVED tally cannot tally anything, and will throw an exception\&. \fBParameters:\fP
.RS 4
\fIneutron\fP the neutron of interest 
.RE
.PP

.PP
Implements \fBTally\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
