.TH "pinspec/src/Fissioner.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Fissioner.h \- 
.PP
The \fBFissioner\fP class for fission neutron emission\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFissioner\fP"
.br
.RI "\fIThe \fBFissioner\fP represents the physics of fission neutron emission\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBFissioner\fP class for fission neutron emission\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 15, 2012 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
