.TH "GeometryCaptureRateTally" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeometryCaptureRateTally \- 
.PP
A class for tallying the capture rate within the geometry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBGeometryTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeometryCaptureRateTally\fP (\fBGeometry\fP *geometry, const char *tally_name=(char *)'')"
.br
.RI "\fI\fBGeometryCaptureRateTally\fP constructor calls the \fBGeometryTally\fP constructor and \fBTally\fP constructors and sets the tally type to CAPTURE_RATE\&. \fP"
.ti -1c
.RI "void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)"
.br
.RI "\fI\fBTally\fP the geometry capture rate by incrementing the tally by $ \frac{\Sigma_c}{\Sigma_t} $ at the neutron's energy\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A class for tallying the capture rate within the geometry\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeometryCaptureRateTally::GeometryCaptureRateTally (\fBGeometry\fP *geometry, const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBGeometryCaptureRateTally\fP constructor calls the \fBGeometryTally\fP constructor and \fBTally\fP constructors and sets the tally type to CAPTURE_RATE\&. \fBParameters:\fP
.RS 4
\fIgeometry\fP a pointer to the geometry within which to tally 
.br
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void GeometryCaptureRateTally::tally (\fBneutron\fP *neutron)\fC [virtual]\fP"

.PP
\fBTally\fP the geometry capture rate by incrementing the tally by $ \frac{\Sigma_c}{\Sigma_t} $ at the neutron's energy\&. \fBParameters:\fP
.RS 4
\fIneutron\fP the neutron of interest 
.RE
.PP

.PP
Implements \fBGeometryTally\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
