.TH "GeometryTally" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeometryTally \- 
.PP
An abstract class for tallies with MATERIAL domain type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBTally\fP\&.
.PP
Inherited by \fBGeometryAbsorptionRateTally\fP, \fBGeometryCaptureRateTally\fP, \fBGeometryCollisionRateTally\fP, \fBGeometryDiffusionRateTally\fP, \fBGeometryElasticRateTally\fP, \fBGeometryFissionRateTally\fP, \fBGeometryFluxTally\fP, \fBGeometryInterCollisionTimeTally\fP, \fBGeometryLeakageRateTally\fP, and \fBGeometryTransportRateTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeometryTally\fP (\fBGeometry\fP *geometry, const char *tally_name=(char *)'')"
.br
.RI "\fI\fBGeometryTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain to GEOMETRY\&. \fP"
.ti -1c
.RI "\fBGeometry\fP * \fBgetGeometry\fP ()"
.br
.RI "\fIReturns the geometry in which this tally resides\&. \fP"
.ti -1c
.RI "virtual void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)=0"
.br
.RI "\fIA method to tally a neutron to be implemented by subclasses\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBGeometry\fP * \fB_geometry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An abstract class for tallies with MATERIAL domain type\&. 

A \fBGeometryTally\fP is for tallying within a geometry\&. The \fBGeometryTally\fP is an abstract class and must be implemented for each tallyType\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GeometryTally::GeometryTally (\fBGeometry\fP *geometry, const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBGeometryTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain to GEOMETRY\&. \fBParameters:\fP
.RS 4
\fIgeometry\fP a pointer to the geometry within which to tally 
.br
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBGeometry\fP* GeometryTally::getGeometry ()\fC [inline]\fP"

.PP
Returns the geometry in which this tally resides\&. \fBReturns:\fP
.RS 4
a pointer to the geometry 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBGeometry\fP* GeometryTally::_geometry\fC [protected]\fP"
A pointer to the geometry in which this tally resides 

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
