.TH "pinspec/src/interpolate.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/interpolate.h \- 
.PP
Utility functions for linear interpolation of 1D functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename U > int \fBfindUpperIndex\fP (T *x, int upper_bound, int lower_bound, U pt)"
.br
.RI "\fIThis function finds the index of the first element in an array that is greater than the given parameter value\&. This is a recursive function and it uses the binary search algorithm to find the upper bound index\&. \fP"
.ti -1c
.RI "template<typename T , typename U , typename P > P \fBlinearInterp\fP (T *x, T *y, int length, U pt)"
.br
.RI "\fIThis function takes in the x and y values of a 1D function and returns the linearly interpolated y value at a particular x-coordinate (pt)\&. It assumes that the values given in x are ordered from least to greatest\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Utility functions for linear interpolation of 1D functions\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 13, 2012 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename T , typename U > int findUpperIndex (T *x, intupper_bound, intlower_bound, Upt)"

.PP
This function finds the index of the first element in an array that is greater than the given parameter value\&. This is a recursive function and it uses the binary search algorithm to find the upper bound index\&. \fBParameters:\fP
.RS 4
\fIx\fP array of values to search 
.br
\fIupper_bound\fP the current upper bound at this level of recursion 
.br
\fIlower_bound\fP the current lower bound at this level of recursion 
.br
\fIpt\fP the value to search for 
.RE
.PP
\fBReturns:\fP
.RS 4
the index of the first element in x which is greater than pt 
.RE
.PP

.SS "template<typename T , typename U , typename P > P linearInterp (T *x, T *y, intlength, Upt)"

.PP
This function takes in the x and y values of a 1D function and returns the linearly interpolated y value at a particular x-coordinate (pt)\&. It assumes that the values given in x are ordered from least to greatest\&. \fBParameters:\fP
.RS 4
\fIx\fP vector of x values 
.br
\fIy\fP vector of y values 
.br
\fIlength\fP the number of x and y 
.br
\fIpt\fP x-coordinate we wish to interpolate 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
