.TH "pinspec/src/Isotope.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Isotope.h \- 
.PP
The \fBIsotope\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIsotope\fP"
.br
.RI "\fIThe \fBIsotope\fP represents a nuclide at some temperature\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBIsotope\fP class\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 13, 2012 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
