.TH "IsotopeTransportRateTally" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsotopeTransportRateTally \- 
.PP
A class for tallying the transport rate for an isotope\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBIsotopeTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsotopeTransportRateTally\fP (\fBIsotope\fP *isotope, const char *tally_name=(char *)'')"
.br
.RI "\fI\fBIsotopeTransportRateTally\fP constructor calls the \fBIsotopeTally\fP constructor and \fBTally\fP constructors and sets the tally type to TRANSPORT_RATE\&. \fP"
.ti -1c
.RI "void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)"
.br
.RI "\fI\fBTally\fP the isotope transport rate by incrementing the tally by $ \frac{\sigma_tr}{\Sigma_t} $ at the neutron's energy\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A class for tallying the transport rate for an isotope\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IsotopeTransportRateTally::IsotopeTransportRateTally (\fBIsotope\fP *isotope, const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBIsotopeTransportRateTally\fP constructor calls the \fBIsotopeTally\fP constructor and \fBTally\fP constructors and sets the tally type to TRANSPORT_RATE\&. \fBParameters:\fP
.RS 4
\fIisotope\fP a pointer to the isotope within which to tally 
.br
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void IsotopeTransportRateTally::tally (\fBneutron\fP *neutron)\fC [virtual]\fP"

.PP
\fBTally\fP the isotope transport rate by incrementing the tally by $ \frac{\sigma_tr}{\Sigma_t} $ at the neutron's energy\&. \fBParameters:\fP
.RS 4
\fIneutron\fP the neutron of interest 
.RE
.PP

.PP
Implements \fBIsotopeTally\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
