.TH "pinspec/log.py" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/log.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpinspec\&.log\fP"
.br
.RI "\fIUtility functions for writing log messages to the screen\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpinspec\&.log\&.py_printf\fP"
.br
.RI "\fIFunction to print a log message to the screen\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.log\&.py_setlevel\fP"
.br
.RI "\fIAssigns the lowest level logging message\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
