.TH "MaterialInterCollisionTimeTally" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialInterCollisionTimeTally \- 
.PP
A class for tallying the time between collision with a material\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBMaterialTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterialInterCollisionTimeTally\fP (\fBMaterial\fP *material, const char *tally_name=(char *)'')"
.br
.RI "\fI\fBMaterialInterCollisionTimeTally\fP constructor calls the \fBMaterialTally\fP constructor and \fBTally\fP constructors and sets the tally type to INTERCOLLISION_TIME\&. \fP"
.ti -1c
.RI "void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)"
.br
.RI "\fI\fBTally\fP the time between collisions by incrementing the tally with the travel time spent by this neutron to reach this collision: \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A class for tallying the time between collision with a material\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaterialInterCollisionTimeTally::MaterialInterCollisionTimeTally (\fBMaterial\fP *material, const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBMaterialInterCollisionTimeTally\fP constructor calls the \fBMaterialTally\fP constructor and \fBTally\fP constructors and sets the tally type to INTERCOLLISION_TIME\&. \fBParameters:\fP
.RS 4
\fImaterial\fP a pointer to the material within which to tally 
.br
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void MaterialInterCollisionTimeTally::tally (\fBneutron\fP *neutron)\fC [virtual]\fP"

.PP
\fBTally\fP the time between collisions by incrementing the tally with the travel time spent by this neutron to reach this collision: $ d = \frac{1}{\Sigma_t} $ $ v = c\sqrt{2Em_n} $ $ time = \frac{d}{v} $ 
.PP
\fBParameters:\fP
.RS 4
\fIneutron\fP the neutron of interest 
.RE
.PP

.PP
Implements \fBMaterialTally\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
