.TH "pinspec/src/Material.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Material.h \- 
.PP
The \fBMaterial\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Isotope\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaterial\fP"
.br
.RI "\fIThe \fBMaterial\fP class represents a collection of isotope objects\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBdensityUnits\fP \fBdensityUnit\fP"
.br
.RI "\fIA unit in which density for isotopes may be expressed\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBdensityUnits\fP { \fBGRAM_CM3\fP, \fBNUM_CM3\fP }"
.br
.RI "\fIUnits in which density for isotopes may be expressed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBMaterial\fP class\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 26, 2012 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
