.TH "MaterialTally" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialTally \- 
.PP
An abstract class for tallies with MATERIAL domain type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBTally\fP\&.
.PP
Inherited by \fBMaterialAbsorptionRateTally\fP, \fBMaterialCaptureRateTally\fP, \fBMaterialCollisionRateTally\fP, \fBMaterialDiffusionRateTally\fP, \fBMaterialElasticRateTally\fP, \fBMaterialFissionRateTally\fP, \fBMaterialFluxTally\fP, \fBMaterialInterCollisionTimeTally\fP, \fBMaterialLeakageRateTally\fP, and \fBMaterialTransportRateTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterialTally\fP (\fBMaterial\fP *material, const char *tally_name=(char *)'')"
.br
.RI "\fI\fBMaterialTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain to MATERIAL\&. \fP"
.ti -1c
.RI "\fBMaterial\fP * \fBgetMaterial\fP ()"
.br
.RI "\fIReturns the material in which this tally resides\&. \fP"
.ti -1c
.RI "virtual void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)=0"
.br
.RI "\fIA method to tally a neutron to be implemented by subclasses\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMaterial\fP * \fB_material\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An abstract class for tallies with MATERIAL domain type\&. 

A \fBMaterialTally\fP is for tallying within a material\&. The \fBMaterialTally\fP is an abstract class and must be implemented for each tallyType\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaterialTally::MaterialTally (\fBMaterial\fP *material, const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBMaterialTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain to MATERIAL\&. \fBParameters:\fP
.RS 4
\fImaterial\fP a pointer to the material within which to tally 
.br
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBMaterial\fP* MaterialTally::getMaterial ()\fC [inline]\fP"

.PP
Returns the material in which this tally resides\&. \fBReturns:\fP
.RS 4
a pointer to the material 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBMaterial\fP* MaterialTally::_material\fC [protected]\fP"
A pointer to the material in which this tally resides 

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
