.TH "neutron" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
neutron \- 
.PP
Represents a neutron in a PINSPEC simulation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Neutron\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_batch_num\fP"
.br
.ti -1c
.RI "float \fB_x\fP"
.br
.ti -1c
.RI "float \fB_y\fP"
.br
.ti -1c
.RI "float \fB_z\fP"
.br
.ti -1c
.RI "float \fB_u\fP"
.br
.ti -1c
.RI "float \fB_v\fP"
.br
.ti -1c
.RI "float \fB_w\fP"
.br
.ti -1c
.RI "float \fB_mu\fP"
.br
.ti -1c
.RI "float \fB_phi\fP"
.br
.ti -1c
.RI "float \fB_energy\fP"
.br
.ti -1c
.RI "bool \fB_alive\fP"
.br
.ti -1c
.RI "\fBRegion\fP * \fB_region\fP"
.br
.ti -1c
.RI "\fBMaterial\fP * \fB_material\fP"
.br
.ti -1c
.RI "\fBIsotope\fP * \fB_isotope\fP"
.br
.ti -1c
.RI "float \fB_old_energy\fP"
.br
.ti -1c
.RI "float \fB_total_xs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a neutron in a PINSPEC simulation\&. 

The neutron struct is the fundamental unit of data needed to represent a neutron in a PINSPEC simulation\&. This struct is useful for passing a neutron from object to object, such as from the \fBGeometry\fP to a \fBRegion\fP to a \fBMaterial\fP and to an \fBIsotope\fP to update the neutron's energy from a collision\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool neutron::_alive"
a boolean representing whether this neutron has been absorbed or not 
.SS "int neutron::_batch_num"
this neutron's batch number in the simulation 
.SS "float neutron::_energy"
the neutron's energy in eV following its most recent collision 
.SS "\fBIsotope\fP* neutron::_isotope"
a pointer to the \fBIsotope\fP with which the neutron most recently collided 
.SS "\fBMaterial\fP* neutron::_material"
a pointer to the \fBMaterial\fP with which the neutron most recently collided 
.SS "float neutron::_mu"
the cosine of the polar angle $\theta$ of this neutron's direction vector: $\mu = cos(\theta)$ 
.SS "float neutron::_old_energy"
the neutron's energy in eV prior to its most recent collision 
.SS "float neutron::_phi"
the azimuthal angle $\phi$ of this neutron's direction vector in the xy-plane 
.SS "\fBRegion\fP* neutron::_region"
a pointer to the Regon in which the neutron most recently collided 
.SS "float neutron::_total_xs"
the total macroscopic cross-section in $cm^{-1}$ of the material in which the neutron collided at its collision energy 
.SS "float neutron::_u"
the component of this neutron's velocity unit vector along the x-axis 
.SS "float neutron::_v"
the component of this neutron's velocity unit vector along the y-axis 
.SS "float neutron::_w"
the component of this neutron's velocity unit vector along the z-axis 
.SS "float neutron::_x"
the x-coordinate of this neutron's location 
.SS "float neutron::_y"
the y-coordinate of this neutron's location 
.SS "float neutron::_z"
the z-coordinate of this neutron's location 

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
