.TH "pinspec/src/Neutron.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Neutron.h \- 
.PP
The neutron C structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBneutron\fP"
.br
.RI "\fIRepresents a neutron in a PINSPEC simulation\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBneutron\fP * \fBinitializeNewNeutron\fP ()"
.br
.RI "\fICreates a new neutron with a set of default attribute values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The neutron C structure\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 13, 2012 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBneutron\fP* initializeNewNeutron ()"

.PP
Creates a new neutron with a set of default attribute values\&. Intializes the neutron with 0\&.0 for its position and direction vector, energy, and batch number and makes the neutron's alive attribute true\&. 
.PP
\fBReturns:\fP
.RS 4
a pointer to the new neutron 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
