.TH "pinspec.process.RIEff" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec.process.RIEff \- 
.PP
An effective resonance integral\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/process\&.py'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fI\fBRIEff\fP constructor\&. \fP"
.ti -1c
.RI "def \fBcomputeRIs\fP"
.br
.RI "\fIComputes the resonance integrals from the two tallies\&. \fP"
.ti -1c
.RI "def \fBsetName\fP"
.br
.RI "\fISets the name of this effective resonance integral\&. \fP"
.ti -1c
.RI "def \fBgetName\fP"
.br
.RI "\fIReturns the name of the \fBRIEff\fP object\&. \fP"
.ti -1c
.RI "def \fBgetNumIntegrals\fP"
.br
.RI "\fIReturns the number of resonance integral energy bands\&. \fP"
.ti -1c
.RI "def \fBgetIntegrals\fP"
.br
.RI "\fIReturns an array of the resonance integral batch averaged values for each tally bin\&. \fP"
.ti -1c
.RI "def \fBgetVariances\fP"
.br
.RI "\fIReturns an array of the resonance integral batch variances for each tally bin\&. \fP"
.ti -1c
.RI "def \fBgetStandardDeviation\fP"
.br
.RI "\fIReturns an array of the resonance integral batch standard deviations for each tally bin\&. \fP"
.ti -1c
.RI "def \fBgetRelativeError\fP"
.br
.RI "\fIReturns an array of the resonance integral batch relative errors for each tally bin\&. \fP"
.ti -1c
.RI "def \fBgetEnergyBandsCenters\fP"
.br
.RI "\fIReturns an array of the resonance integral energy band centers for each tally bin\&. \fP"
.ti -1c
.RI "def \fBgetEnergyBands\fP"
.br
.RI "\fIReturns an array of the resonance integral energy bands\&. \fP"
.ti -1c
.RI "def \fBgetRITally\fP"
.br
.RI "\fIReturns a reference to this \fBRIEff\fP object\&. \fP"
.ti -1c
.RI "def \fBprintRI\fP"
.br
.RI "\fIPrints a formatted table of the effective resonance integrals to the screen\&. \fP"
.ti -1c
.RI "def \fBoutputRItoFile\fP"
.br
.RI "\fIPrints the resonance integral data and batch statistics to a file\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_name\fP"
.br
.RI "\fIThe name of the effective resonance integral\&. \fP"
.ti -1c
.RI "\fB_RI\fP"
.br
.RI "\fIThe DERIVED tally type for the effective resonance integral data\&. \fP"
.ti -1c
.RI "\fB_flux\fP"
.br
.RI "\fIThe FLUX tally used to compute the effective resonance integral\&. \fP"
.ti -1c
.RI "\fB_rate\fP"
.br
.RI "\fIThe REACTION_RATE tally used to compute the effective resonance integral\&. \fP"
.ti -1c
.RI "\fB_num_RIs\fP"
.br
.RI "\fIThe number of resonance integral energy bands\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An effective resonance integral\&. 

This class represents an effective resonance integral computed by a PINSPEC monte carlo simulation\&. Two tallies - one reaction rate and one flux - are required to form a \fBRIEff\fP class object\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pinspec\&.process\&.RIEff\&.__init__ (self, tally1, tally2, name = \fC''\fP)"

.PP
\fBRIEff\fP constructor\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.br
\fItally1\fP one of the tallies needed to compute an $ RI_{eff} $ 
.br
\fItally2\fP one of the tallies needed to compute an $ RI_{eff} $ 
.br
\fIname\fP an optional string for the name of the resonance integral 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def pinspec\&.process\&.RIEff\&.computeRIs (self, tally1, tally2)"

.PP
Computes the resonance integrals from the two tallies\&. This method checks that one of the tallies input is a reaction rate and the other is a flux, with the same bin edges\&. If the batch statistics for both tallies have been computed, it computes the resonance integral as follows:
.PP
.PP
.nf
edges = getTallyEdges(tally1)
log_array = numpy\&.log(edges[1:] / edges[0:edges\&.size-1])
RI_eff = (reaction_rate / flux)\&.multiplyDoubles(log_array)
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.br
\fItally1\fP one of the tallies needed to compute an $ RI_{eff} $ 
.br
\fItally2\fP one of the tallies needed to compute an $ RI_{eff} $ 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getEnergyBands (self)"

.PP
Returns an array of the resonance integral energy bands\&. The energy bands are the tally bin edges for the reaction rate and flux tally forming this effective resonance integral\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integral energy bands (eV) 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getEnergyBandsCenters (self)"

.PP
Returns an array of the resonance integral energy band centers for each tally bin\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integral energy band centers 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getIntegrals (self)"

.PP
Returns an array of the resonance integral batch averaged values for each tally bin\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integrals 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getName (self)"

.PP
Returns the name of the \fBRIEff\fP object\&. Returns an empty string if no name has been specified by the user\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a string with the name of the \fBRIEff\fP 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getNumIntegrals (self)"

.PP
Returns the number of resonance integral energy bands\&. The number of integrals is equivalent to the number of tally bins for the reaction rate and flux tallies\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of resonance integrals 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getRelativeError (self)"

.PP
Returns an array of the resonance integral batch relative errors for each tally bin\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integral relative errors 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getRITally (self)"

.PP
Returns a reference to this \fBRIEff\fP object\&. \fBParameters:\fP
.RS 4
\fIself\fP \fBRIEff\fP the object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a reference to the \fBRIEff\fP object 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getStandardDeviation (self)"

.PP
Returns an array of the resonance integral batch standard deviations for each tally bin\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integral standard deviations 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.getVariances (self)"

.PP
Returns an array of the resonance integral batch variances for each tally bin\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integral variances 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.outputRItoFile (self, filename = \fC''\fP)"

.PP
Prints the resonance integral data and batch statistics to a file\&. Since the effective resonance integral is stored as a DERIVED tally type, this method prints the resonance integral data to a file using the \fBTally::outputBatchStatistics()\fP method\&. An auto-generated filename will be created with the format 'tally-#\&.data' where # is an auto-incremented integer for each tally output data file created\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.br
\fIfilename\fP An optional filename for the output file 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.printRI (self, uncertainties = \fCFalse\fP)"

.PP
Prints a formatted table of the effective resonance integrals to the screen\&. The resonance integrals and their uncertainties (optional) will be printed as a formatted table to the screen\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.br
\fIuncertainties\fP whether or not to print tally statistics (default is false) 
.RE
.PP
\fBReturns:\fP
.RS 4
a reference to the \fBRIEff\fP object 
.RE
.PP

.SS "def pinspec\&.process\&.RIEff\&.setName (self, name = \fC''\fP)"

.PP
Sets the name of this effective resonance integral\&. This is useful when one wishes to print the resonance integral values to the screen or a file since it will be identifiable by the user-defined name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRIEff\fP object pointer 
.br
\fIname\fP the name of the \fBRIEff\fP object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
