.TH "pinspec.process.RITrue" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec.process.RITrue \- 
.PP
A true resonance integral\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/process\&.py'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fI\fBRITrue\fP constructor\&. \fP"
.ti -1c
.RI "def \fBsetName\fP"
.br
.RI "\fISets the name of the true resonance integral\&. \fP"
.ti -1c
.RI "def \fBcomputeRIs\fP"
.br
.RI "\fIComputes the true resonance integrals for an isotopic reaction rate\&. \fP"
.ti -1c
.RI "def \fBgetName\fP"
.br
.RI "\fIReturns the name of the \fBRITrue\fP object\&. \fP"
.ti -1c
.RI "def \fBgetNumIntegrals\fP"
.br
.RI "\fIReturns the number of resonance integral energy bands\&. \fP"
.ti -1c
.RI "def \fBgetIntegrals\fP"
.br
.RI "\fIReturns an array of the resonance integrals for each energy band\&. \fP"
.ti -1c
.RI "def \fBgetEnergyBandsCenters\fP"
.br
.RI "\fIReturns an array of the centers of each energy band\&. \fP"
.ti -1c
.RI "def \fBgetEnergyBands\fP"
.br
.RI "\fIReturns an array of the energy bands\&. \fP"
.ti -1c
.RI "def \fBprintRIs\fP"
.br
.RI "\fIPrints a formatted table of the true resonance integrals to the screen\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_name\fP"
.br
.RI "\fIThe name of the effective resonance integral\&. \fP"
.ti -1c
.RI "\fB_isotope\fP"
.br
.RI "\fIThe isotope for this resonance integral\&. \fP"
.ti -1c
.RI "\fB_reaction\fP"
.br
.RI "\fIThe reaction rate for this resonance integral (ie, 'capture') \fP"
.ti -1c
.RI "\fB_num_RIs\fP"
.br
.RI "\fIThe number of resonance integrals\&. \fP"
.ti -1c
.RI "\fB_RIs\fP"
.br
.RI "\fIThe numpy array of resonance integral values\&. \fP"
.ti -1c
.RI "\fB_energy_bands\fP"
.br
.RI "\fIThe numpy array of energy band values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A true resonance integral\&. 

This class represents the true resonance integral computed from a $ \frac{1}{E} $ spectrum\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pinspec\&.process\&.RITrue\&.__init__ (self, isotope, bands, reaction = \fC'capture'\fP, name = \fC''\fP)"

.PP
\fBRITrue\fP constructor\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.br
\fIisotope\fP a pointer to the isotope of interest 
.br
\fIbands\fP an array of the energy bands for each resonance integral 
.br
\fIreaction\fP an optional argument string with the reaction rate type 
.br
\fIname\fP an optional argument string for the resonance integral name 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def pinspec\&.process\&.RITrue\&.computeRIs (self, bands, reaction)"

.PP
Computes the true resonance integrals for an isotopic reaction rate\&. This method computes an infinite dilute resonance integral for each of the user-defined energy bands for some isotopic reaction rate using numerical integration as follows:
.PP
$ \int\limits_{E_{i-1}}^{E_i} \sigma_{j}(E) \frac{1}{E} \mathrm{d}E $.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.br
\fIbands\fP an array of the energy bands for each resonance integral 
.br
\fIreaction\fP an optional argument string with the reaction rate type 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.getEnergyBands (self)"

.PP
Returns an array of the energy bands\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the values defining the energy bands (eV) 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.getEnergyBandsCenters (self)"

.PP
Returns an array of the centers of each energy band\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the energy band centers (eV) 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.getIntegrals (self)"

.PP
Returns an array of the resonance integrals for each energy band\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a numpy array of the resonance integrals 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.getName (self)"

.PP
Returns the name of the \fBRITrue\fP object\&. Returns an empty string if no name has been specified by the user\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a string with the name of the \fBRITrue\fP 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.getNumIntegrals (self)"

.PP
Returns the number of resonance integral energy bands\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of resonance integrals 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.printRIs (self)"

.PP
Prints a formatted table of the true resonance integrals to the screen\&. \fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
a reference to the \fBRITrue\fP object 
.RE
.PP

.SS "def pinspec\&.process\&.RITrue\&.setName (self, name = \fC''\fP)"

.PP
Sets the name of the true resonance integral\&. This is useful when one wishes to print the resonance integral values to the screen or a file since it will be identifiable by the user-defined name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP the \fBRITrue\fP object pointer 
.br
\fIname\fP the name of the \fBRITrue\fP object 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "pinspec\&.process\&.RITrue\&._reaction\fC [private]\fP"

.PP
The reaction rate for this resonance integral (ie, 'capture') The reaction rate type (ie, 'capture') 

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
