.TH "pinspec/process.py" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/process.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpinspec\&.process\&.RIEff\fP"
.br
.RI "\fIAn effective resonance integral\&. \fP"
.ti -1c
.RI "class \fBpinspec\&.process\&.RITrue\fP"
.br
.RI "\fIA true resonance integral\&. \fP"
.ti -1c
.RI "class \fBpinspec\&.process\&.GroupXS\fP"
.br
.RI "\fIA multi-group cross-section for a certain reaction rate\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpinspec\&.process\fP"
.br
.RI "\fIThe process module provides utility functions to retrieve data from PINSPEC's C++ classes, in particular, tally data\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyCenters\fP"
.br
.RI "\fIReturns an array of the center values for a tally's bins\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyEdges\fP"
.br
.RI "\fIReturns an array of the bin edge values for a tally's bins\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyBatchMu\fP"
.br
.RI "\fIReturns an array of the batch averages for the tally's bins\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyBatchVariances\fP"
.br
.RI "\fIReturns an array of the batch variances for a tally's bins\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyBatchStdDev\fP"
.br
.RI "\fIReturns an array of the batch standard deviations for a tally's bins\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyBatchRelErr\fP"
.br
.RI "\fIReturns an array of the batch relative errors for a tally's bins\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.getTallyBatchStatistics\fP"
.br
.RI "\fIReturns a 2D array of the tally's batch statistics\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.printTallies\fP"
.br
.RI "\fIPrints formatted tally batch-averaged data to the screen as a table\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.computeMeanNumCollisions\fP"
.br
.RI "\fIComputes the mean number of collisions for a neutron before absorption\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.computeMeanNeutronLifetime\fP"
.br
.RI "\fIComputes the mean neutron lifetime (seconds) before absorption\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.process\&.printRIs\fP"
.br
.RI "\fIPrints a formatted table for an array of true and/or effectrive resonance integrals to the screen\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
