.TH "pinspec/src/Region.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Region.h \- 
.PP
The \fBRegion\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegion\fP"
.br
.RI "\fIThe region class represents a region in 2D space\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBregionTypes\fP \fBregionType\fP"
.br
.RI "\fI\fBRegion\fP spatial type\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBregionTypes\fP { \fBFUEL\fP, \fBMODERATOR\fP, \fBINFINITE\fP }"
.br
.RI "\fISpatial Types of regions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBRegion\fP class\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 15, 2013 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBregionTypes\fP"

.PP
Spatial Types of regions\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFUEL \fP\fP
A fuel region 
.TP
\fB\fIMODERATOR \fP\fP
A moderator region 
.TP
\fB\fIINFINITE \fP\fP
An infinite medium region 
.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
