.TH "RegionTally" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegionTally \- 
.PP
An abstract class for tallies with REGION domain type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Tally\&.h'\fP
.PP
Inherits \fBTally\fP\&.
.PP
Inherited by \fBRegionAbsorptionRateTally\fP, \fBRegionCaptureRateTally\fP, \fBRegionCollisionRateTally\fP, \fBRegionDiffusionRateTally\fP, \fBRegionElasticRateTally\fP, \fBRegionFissionRateTally\fP, \fBRegionFluxTally\fP, \fBRegionInterCollisionTimeTally\fP, \fBRegionLeakageRateTally\fP, and \fBRegionTransportRateTally\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegionTally\fP (\fBRegion\fP *region, const char *tally_name=(char *)'')"
.br
.RI "\fI\fBRegionTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain to REGION\&. \fP"
.ti -1c
.RI "\fBRegion\fP * \fBgetRegion\fP ()"
.br
.RI "\fIReturns the region in which this tally resides\&. \fP"
.ti -1c
.RI "virtual void \fBtally\fP (\fBneutron\fP *\fBneutron\fP)=0"
.br
.RI "\fIA method to tally a neutron to be implemented by subclasses\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRegion\fP * \fB_region\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An abstract class for tallies with REGION domain type\&. 

A \fBRegionTally\fP is for tallying within a region\&. The \fBRegionTally\fP is an abstract class and must be implemented for each tallyType\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RegionTally::RegionTally (\fBRegion\fP *region, const char *tally_name = \fC(char*)''\fP)\fC [inline]\fP"

.PP
\fBRegionTally\fP constructor calls the \fBTally\fP constructor and sets the tally domain to REGION\&. \fBParameters:\fP
.RS 4
\fIregion\fP a pointer to the region within which to tally 
.br
\fItally_name\fP a character array for the tally name (optional) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBRegion\fP* RegionTally::getRegion ()\fC [inline]\fP"

.PP
Returns the region in which this tally resides\&. \fBReturns:\fP
.RS 4
a pointer to the region 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBRegion\fP* RegionTally::_region\fC [protected]\fP"
A pointer to the region in which this tally resides 

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
