.TH "pinspec/slbw.py" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/slbw.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpinspec\&.slbw\fP"
.br
.RI "\fIThe slbw module provides utility functions to generate resonant cross-sections using the Single-Level Breit-Wigner formalism\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpinspec\&.slbw\&.SLBWXS\fP"
.br
.RI "\fIFunction to create resonant capture and scatter cross-sections\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.slbw\&.convert\fP"
.br
.RI "\fIFunction to convert a string into a float\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.slbw\&.parse\fP"
.br
.RI "\fIFunction to parse a string and convert into resonance parameters\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.slbw\&.generatePotentialScattering\fP"
.br
.RI "\fIFunction to generate a potential scattering cross-section for an isotope based on data in a resonance parameters file\&. \fP"
.ti -1c
.RI "def \fBpinspec\&.slbw\&.compareXS\fP"
.br
.RI "\fIFunction to generate a plot of the SLBW generated cross-section along with the ENDF-VII version of the cross-section for comparison\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
