.TH "pinspec/src/TallyFactory.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/TallyFactory.h \- 
.PP
The \fBTallyFactory\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Tally\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTallyFactory\fP"
.br
.RI "\fIA utility class for creating instances of tallies\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBTallyFactory\fP class\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 19, 2013 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
