.TH "pinspec/src/TallyBank.h" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/TallyBank.h \- 
.PP
The \fBTallyBank\fP static class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTallyBank\fP"
.br
.RI "\fIThe \fBTallyBank\fP contains all tallies for a simulation\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBoutput_file_num\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBTallyBank\fP static class\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd\&.mit\&.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 20, 2013 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int output_file_num"
The filename for this tally's output file of batch-based statistics 
.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
