.TH "pinspec/src/Tally.h" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Tally.h \- 
.PP
The \fBTally\fP superclass and subclasses\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTally\fP"
.br
.RI "\fIA \fBTally\fP reprsents a set of bins for tallying some quantity\&. \fP"
.ti -1c
.RI "class \fBIsotopeTally\fP"
.br
.RI "\fIAn abstract class for tallies with ISOTOPE domain type\&. \fP"
.ti -1c
.RI "class \fBMaterialTally\fP"
.br
.RI "\fIAn abstract class for tallies with MATERIAL domain type\&. \fP"
.ti -1c
.RI "class \fBRegionTally\fP"
.br
.RI "\fIAn abstract class for tallies with REGION domain type\&. \fP"
.ti -1c
.RI "class \fBGeometryTally\fP"
.br
.RI "\fIAn abstract class for tallies with MATERIAL domain type\&. \fP"
.ti -1c
.RI "class \fBIsotopeCollisionRateTally\fP"
.br
.RI "\fIA class for tallying the collision rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialCollisionRateTally\fP"
.br
.RI "\fIA class for tallying the collision rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionCollisionRateTally\fP"
.br
.RI "\fIA class for tallying the collision rate within a region\&. \fP"
.ti -1c
.RI "class \fBGeometryCollisionRateTally\fP"
.br
.RI "\fIA class for tallying the collision rate within the geometry\&. \fP"
.ti -1c
.RI "class \fBIsotopeElasticRateTally\fP"
.br
.RI "\fIA class for tallying the elastic scattering rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialElasticRateTally\fP"
.br
.RI "\fIA class for tallying the elastic scattering rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionElasticRateTally\fP"
.br
.RI "\fIA class for tallying the elastic scattering rate within a region\&. \fP"
.ti -1c
.RI "class \fBGeometryElasticRateTally\fP"
.br
.RI "\fIA class for tallying the elastic scattering rate within the geometry\&. \fP"
.ti -1c
.RI "class \fBIsotopeAbsorptionRateTally\fP"
.br
.RI "\fIA class for tallying the absorption rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialAbsorptionRateTally\fP"
.br
.RI "\fIA class for tallying the absorption rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionAbsorptionRateTally\fP"
.br
.RI "\fIA class for tallying the absorption rate within a region\&. \fP"
.ti -1c
.RI "class \fBGeometryAbsorptionRateTally\fP"
.br
.RI "\fIA class for tallying the absorption within the geometry\&. \fP"
.ti -1c
.RI "class \fBIsotopeCaptureRateTally\fP"
.br
.RI "\fIA class for tallying the capture rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialCaptureRateTally\fP"
.br
.RI "\fIA class for tallying the collision rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionCaptureRateTally\fP"
.br
.RI "\fIA class for tallying the capture rate within a region\&. \fP"
.ti -1c
.RI "class \fBGeometryCaptureRateTally\fP"
.br
.RI "\fIA class for tallying the capture rate within the geometry\&. \fP"
.ti -1c
.RI "class \fBIsotopeFissionRateTally\fP"
.br
.RI "\fIA class for tallying the fission rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialFissionRateTally\fP"
.br
.RI "\fIA class for tallying the capture rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionFissionRateTally\fP"
.br
.RI "\fIA class for tallying the fission rate within a region\&.\&. \fP"
.ti -1c
.RI "class \fBGeometryFissionRateTally\fP"
.br
.RI "\fIA class for tallying the capture rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBIsotopeTransportRateTally\fP"
.br
.RI "\fIA class for tallying the transport rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialTransportRateTally\fP"
.br
.RI "\fIA class for tallying the transport rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionTransportRateTally\fP"
.br
.RI "\fIA class for tallying the transport rate within a region\&. \fP"
.ti -1c
.RI "class \fBGeometryTransportRateTally\fP"
.br
.RI "\fIA class for tallying the transport rate within the geometry\&. \fP"
.ti -1c
.RI "class \fBIsotopeDiffusionRateTally\fP"
.br
.RI "\fIA class for tallying the diffusion rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialDiffusionRateTally\fP"
.br
.RI "\fIA class for tallying the diffusion rate within a material\&. \fP"
.ti -1c
.RI "class \fBRegionDiffusionRateTally\fP"
.br
.RI "\fIA class for tallying the diffusion rate within a region\&. \fP"
.ti -1c
.RI "class \fBGeometryDiffusionRateTally\fP"
.br
.RI "\fIA class for tallying the capture rate for an isotope\&. \fP"
.ti -1c
.RI "class \fBMaterialLeakageRateTally\fP"
.br
.RI "\fIA class for tallying the leakage rate for the regions filled by a material\&. \fP"
.ti -1c
.RI "class \fBRegionLeakageRateTally\fP"
.br
.RI "\fIA class for tallying the leakage rate for a region\&. \fP"
.ti -1c
.RI "class \fBGeometryLeakageRateTally\fP"
.br
.RI "\fIA class for tallying the leakage rate for the geometry\&. \fP"
.ti -1c
.RI "class \fBMaterialFluxTally\fP"
.br
.RI "\fIA class for tallying the flux in all regions filled by a material\&. \fP"
.ti -1c
.RI "class \fBRegionFluxTally\fP"
.br
.RI "\fIA class for tallying the flux for a region\&. \fP"
.ti -1c
.RI "class \fBGeometryFluxTally\fP"
.br
.RI "\fIA class for tallying the flux for the geometry\&. \fP"
.ti -1c
.RI "class \fBMaterialInterCollisionTimeTally\fP"
.br
.RI "\fIA class for tallying the time between collision with a material\&. \fP"
.ti -1c
.RI "class \fBRegionInterCollisionTimeTally\fP"
.br
.RI "\fIA class for tallying the time between collisions for the region\&. \fP"
.ti -1c
.RI "class \fBGeometryInterCollisionTimeTally\fP"
.br
.RI "\fIA class for tallying the time between collisions for the geometry\&. \fP"
.ti -1c
.RI "class \fBDerivedTally\fP"
.br
.RI "\fIA class for tallies resulting from tally arithmetic operations\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNEUTRON_MASS\fP   939565378"
.br
.ti -1c
.RI "#define \fBLIGHT_SPEED\fP   299792458"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBtallyDomainTypes\fP \fBtallyDomainType\fP"
.br
.RI "\fIA domain type within which a tally may reside\&. \fP"
.ti -1c
.RI "typedef enum \fBtriggerTypes\fP \fBtriggerType\fP"
.br
.RI "\fIThe type of precision trigger for a tally object\&. \fP"
.ti -1c
.RI "typedef enum \fBtallyTypes\fP \fBtallyType\fP"
.br
.RI "\fIThe types of tallies which may be instantiated and used in a PINSPEC simulation\&. \fP"
.ti -1c
.RI "typedef enum \fBbinSpacingTypes\fP \fBbinSpacingType\fP"
.br
.RI "\fIThe spacing between bin edges for a tally\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtallyDomainTypes\fP { \fBMATERIAL\fP, \fBISOTOPE\fP, \fBREGION\fP, \fBGEOMETRY\fP, \fBUNDEFINED\fP }"
.br
.RI "\fIThe types of domains in which tally may reside\&. \fP"
.ti -1c
.RI "enum \fBtriggerTypes\fP { \fBVARIANCE\fP, \fBSTANDARD_DEVIATION\fP, \fBRELATIVE_ERROR\fP, \fBNONE\fP }"
.br
.RI "\fIThe type of precision trigger for a tally object\&. \fP"
.ti -1c
.RI "enum \fBtallyTypes\fP { \fBFLUX\fP, \fBLEAKAGE_RATE\fP, \fBCOLLISION_RATE\fP, \fBINTERCOLLISION_TIME\fP, \fBELASTIC_RATE\fP, \fBABSORPTION_RATE\fP, \fBCAPTURE_RATE\fP, \fBFISSION_RATE\fP, \fBTRANSPORT_RATE\fP, \fBDIFFUSION_RATE\fP, \fBDERIVED\fP }"
.br
.RI "\fIThe types of tallies which may be instantiated and used in a PINSPEC simulation\&. \fP"
.ti -1c
.RI "enum \fBbinSpacingTypes\fP { \fBEQUAL\fP, \fBLOGARITHMIC\fP, \fBOTHER\fP }"
.br
.RI "\fIThe spacing between bin edges for tallies\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTally\fP * \fBcreateTally\fP (\fBGeometry\fP *geometry, \fBtallyType\fP tally_type, const char *tally_name=(char *)'')"
.br
.RI "\fIMethod to create a tally for some tally type within the geometry\&. \fP"
.ti -1c
.RI "\fBTally\fP * \fBcreateTally\fP (\fBRegion\fP *region, \fBtallyType\fP tally_type, const char *tally_name=(char *)'')"
.br
.RI "\fIMethod to create a tally for some tally type within a region\&. \fP"
.ti -1c
.RI "\fBTally\fP * \fBcreateTally\fP (\fBMaterial\fP *material, \fBtallyType\fP tally_type, const char *tally_name=(char *)'')"
.br
.RI "\fIMethod to create a tally for some tally type within a material\&. \fP"
.ti -1c
.RI "\fBTally\fP * \fBcreateTally\fP (\fBIsotope\fP *isotope, \fBtallyType\fP tally_type, const char *tally_name=(char *)'')"
.br
.RI "\fIMethod to create a tally for some tally type within an isotope\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBTally\fP superclass and subclasses\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd\&.mit\&.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
March 4, 2013 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define LIGHT_SPEED   299792458"
The speed of light in meters per second 
.SS "#define NEUTRON_MASS   939565378"
Mass of a neutron in $ \frac{eV}{c^2} $ 
.SH "Typedef Documentation"
.PP 
.SS "\fBtriggerType\fP"

.PP
The type of precision trigger for a tally object\&. Precision triggers represent a threshold on the level of precision the user requires before ending the simulation\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBbinSpacingTypes\fP"

.PP
The spacing between bin edges for tallies\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIEQUAL \fP\fP
Equally spaced bins 
.TP
\fB\fILOGARITHMIC \fP\fP
Logarithmically spaced bins 
.TP
\fB\fIOTHER \fP\fP
Bin edges without a specified pattern 
.SS "enum \fBtallyDomainTypes\fP"

.PP
The types of domains in which tally may reside\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIMATERIAL \fP\fP
A tally may reside within a material 
.TP
\fB\fIISOTOPE \fP\fP
A tally may reside within an isotope 
.TP
\fB\fIREGION \fP\fP
A tally may reside within a region 
.TP
\fB\fIGEOMETRY \fP\fP
A tally may reside within the entire geometry 
.TP
\fB\fIUNDEFINED \fP\fP
A tally may have an undefined domain - only used for DERIVED tally types 
.SS "enum \fBtallyTypes\fP"

.PP
The types of tallies which may be instantiated and used in a PINSPEC simulation\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFLUX \fP\fP
A tally of the flux 
.TP
\fB\fILEAKAGE_RATE \fP\fP
A tally of the leakage rate 
.TP
\fB\fICOLLISION_RATE \fP\fP
A tally of the collision rate 
.TP
\fB\fIINTERCOLLISION_TIME \fP\fP
A tally of the intercollision time 
.TP
\fB\fIELASTIC_RATE \fP\fP
A tally of the elastic scattering rate 
.TP
\fB\fIABSORPTION_RATE \fP\fP
A tally of the absorption rate 
.TP
\fB\fICAPTURE_RATE \fP\fP
A tally of the capture rate 
.TP
\fB\fIFISSION_RATE \fP\fP
A tally of the fission rate 
.TP
\fB\fITRANSPORT_RATE \fP\fP
A tally of the transport rate 
.TP
\fB\fIDIFFUSION_RATE \fP\fP
A tally of the diffusion rate 
.TP
\fB\fIDERIVED \fP\fP
A derived tally type - used to define the tally returned from tally arithmetic such as would be the case in Python:
.PP
.PP
.nf
derived_tally = tally1 + tally2
.fi
.PP
 
.SS "enum \fBtriggerTypes\fP"

.PP
The type of precision trigger for a tally object\&. Precision triggers represent a threshold on the level of precision the user requires before ending the simulation\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIVARIANCE \fP\fP
A precision trigger on the maximum variance for a tally 
.TP
\fB\fISTANDARD_DEVIATION \fP\fP
A precision trigger on the maximum standard deviation for a tally 
.TP
\fB\fIRELATIVE_ERROR \fP\fP
A precision trigger on the maximum relative error for a tally 
.TP
\fB\fINONE \fP\fP
The absence of a precision trigger for a tally 
.SH "Function Documentation"
.PP 
.SS "\fBTally\fP* createTally (\fBGeometry\fP *geometry, \fBtallyType\fPtally_type, const char *tally_name)"

.PP
Method to create a tally for some tally type within the geometry\&. \fBParameters:\fP
.RS 4
\fIgeometry\fP a pointer to the geometry within which to tally 
.br
\fItally_type\fP the type of tally (ie, FLUX, CAPTURE_RATE, etc\&.) 
.br
\fItally_name\fP a character array for the name of the tally 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the newly created tally 
.RE
.PP

.SS "\fBTally\fP* createTally (\fBRegion\fP *region, \fBtallyType\fPtally_type, const char *tally_name)"

.PP
Method to create a tally for some tally type within a region\&. \fBParameters:\fP
.RS 4
\fIregion\fP a pointer to the region within which to tally 
.br
\fItally_type\fP the type of tally (ie, FLUX, CAPTURE_RATE, etc\&.) 
.br
\fItally_name\fP a character array for the name of the tally 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the newly created tally 
.RE
.PP

.SS "\fBTally\fP* createTally (\fBMaterial\fP *material, \fBtallyType\fPtally_type, const char *tally_name)"

.PP
Method to create a tally for some tally type within a material\&. \fBParameters:\fP
.RS 4
\fImaterial\fP a pointer to the material within which to tally 
.br
\fItally_type\fP the type of tally (ie, FLUX, CAPTURE_RATE, etc\&.) 
.br
\fItally_name\fP a character array for the name of the tally 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the newly created tally 
.RE
.PP

.SS "\fBTally\fP* createTally (\fBIsotope\fP *isotope, \fBtallyType\fPtally_type, const char *tally_name)"

.PP
Method to create a tally for some tally type within an isotope\&. \fBParameters:\fP
.RS 4
\fIisotope\fP a pointer to the isotope to tally 
.br
\fItally_type\fP the type of tally (ie, FLUX, CAPTURE_RATE, etc\&.) 
.br
\fItally_name\fP a character array for the name of the tally 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the newly created tally 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
