.TH "pinspec/src/Timer.h" 3 "Thu Apr 11 2013" "Version v0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinspec/src/Timer.h \- 
.PP
The \fBTimer\fP static class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer\fP"
.br
.RI "\fIThe \fBTimer\fP represents a simulation stopwatch\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBTimer\fP static class\&. 

\fBAuthor:\fP
.RS 4
William Boyd (wboyd@mit.edu) 
.RE
.PP
\fBDate:\fP
.RS 4
January 2, 2012 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
