.TH "XPlane" 3 "Wed Apr 10 2013" "Version 0.1" "PINSPEC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XPlane \- 
.PP
The \fBXPlane\fP is a plane perpendicular to the y-axis\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'pinspec/src/Surface\&.h'\fP
.PP
Inherits \fBSurface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXPlane\fP ()"
.br
.RI "\fIThe \fBXPlane\fP constructor\&. \fP"
.ti -1c
.RI "virtual \fB~XPlane\fP ()"
.br
.RI "\fI\fBXPlane\fP destructor\&. \fP"
.ti -1c
.RI "float \fBgetX\fP ()"
.br
.RI "\fIReturns the x-coordinate of the plane's intersection point with the x-axis\&. \fP"
.ti -1c
.RI "void \fBsetX\fP (float x)"
.br
.RI "\fISets the x-coordinate of the plane's intersection point with the x-axis\&. \fP"
.ti -1c
.RI "float \fBcomputeNearestDistance\fP (\fBneutron\fP *\fBneutron\fP)"
.br
.RI "\fIComputes the nearest distance to the \fBXPlane\fP along a neutron's trajectory\&. \fP"
.ti -1c
.RI "bool \fBonSurface\fP (\fBneutron\fP *\fBneutron\fP)"
.br
.RI "\fIChecks whether a neutron is on the \fBXPlane\fP\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fB_x\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBXPlane\fP is a plane perpendicular to the y-axis\&. 

The \fBXPlane\fP represents planes perpendicular to the x-axis using the quadratic surface formulation\&. The \fBXPlane\fP is a \fBSurface\fP subclass\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XPlane::XPlane ()"

.PP
The \fBXPlane\fP constructor\&. Assigns a default value of x=0 for the x-axis intersection point\&. 
.SH "Member Function Documentation"
.PP 
.SS "float XPlane::computeNearestDistance (\fBneutron\fP *neutron)\fC [virtual]\fP"

.PP
Computes the nearest distance to the \fBXPlane\fP along a neutron's trajectory\&. \fBParameters:\fP
.RS 4
\fIneutron\fP a pointer to a Neutron struct 
.RE
.PP

.PP
Implements \fBSurface\fP\&.
.SS "float XPlane::getX ()"

.PP
Returns the x-coordinate of the plane's intersection point with the x-axis\&. \fBReturns:\fP
.RS 4
the x-coordinate of the intersection point 
.RE
.PP

.SS "bool XPlane::onSurface (\fBneutron\fP *neutron)\fC [virtual]\fP"

.PP
Checks whether a neutron is on the \fBXPlane\fP\&. The threshold used to compute whether or not a neutron is on the on the \fBXPlane\fP is 1E-6 for the difference between the x-coordinate of the neutron's position and the location of the \fBXPlane\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIneutron\fP the neutron of interest 
.RE
.PP
\fBReturns:\fP
.RS 4
true if on the \fBXPlane\fP, otherwise false 
.RE
.PP

.PP
Implements \fBSurface\fP\&.
.SS "void XPlane::setX (floatx)"

.PP
Sets the x-coordinate of the plane's intersection point with the x-axis\&. \fBParameters:\fP
.RS 4
\fIx\fP the x-coordinate of the intersectiont point 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float XPlane::_x\fC [private]\fP"
The location of the plane's intersection with the x-axis 

.SH "Author"
.PP 
Generated automatically by Doxygen for PINSPEC from the source code\&.
